#!/bin/bash

in_text=$1
out_image=$2
x_offset="275"
y_offset="285"
tmp_dir="/tmp/"
in_icon_base="base.png"
in_text_container="box.png"
out_text="${tmp_dir}text.png"
out_text_shadow="${tmp_dir}shadow.png"
out_text_container="${tmp_dir}text_box.png"

# Build the icon in layers

# White text
convert \
    -background transparent \
    -fill white \
    -pointsize 120 \
    label:$in_text \
    $out_text

# Text shadow
convert \
    -background transparent \
    -fill black \
    -pointsize 120 \
    label:$in_text \
    $out_text_shadow
convert $out_text_shadow \
    -gaussian-blur 5x5 \
    $out_text_shadow

convert $out_text \
    -colorize 0% \
    miff:- | \
        composite \
            -dissolve 100 \
            - $out_text_shadow \
    $out_text

# Stick it all together
convert $out_text \
    -fill white \
    -colorize 0% \
    miff:- | \
        composite \
            -dissolve 100 \
            -geometry +$x_offset+$y_offset \
            - $in_text_container \
    $out_text_container

convert $out_text_container \
    -fill white \
    -colorize 0% \
    miff:- | \
        composite \
            -dissolve 100 \
            -gravity southeast \
            - $in_icon_base \
    $out_image

# Clean up
rm $out_text
rm $out_text_shadow
rm $out_text_container
